# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel

cache:
  directories:
    - $HOME/.cmdstanr
  packages: true

r_github_packages:
  - r-lib/covr

warnings_are_errors: true
env:
  - NOT_CRAN=true _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - sudo bash inst/make_cmdstan.sh -j2 -o

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = list("R/zzz.R"))'
